#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define MPU6050_SDA_GPIO 21
#define MPU6050_SCL_GPIO 22
#define MPU6050_INT_GPIO 19

#define LED_GPIO 26
#define BUZZER_GPIO 27
#define BUTTON_GPIO 32

#define MPU6050_I2C_ADDR 0x68

#define SENSOR_SAMPLE_RATE_HZ 50
#define SENSOR_SAMPLE_PERIOD_MS 20

#define ENABLE_SENSOR_CSV_LOG 0
#define SENSOR_CSV_LABEL "fall_soft"

#define ENABLE_EDGE_IMPULSE_MODEL 1
#define EDGE_IMPULSE_FALL_THRESHOLD 0.80f
#define EDGE_IMPULSE_REQUIRED_CONSECUTIVE_WINDOWS 1

#endif // APP_CONFIG_H
