#ifndef TELEGRAM_CREDENTIALS_EXAMPLE_H
#define TELEGRAM_CREDENTIALS_EXAMPLE_H

#define TELEGRAM_BOT_TOKEN "YOUR_TELEGRAM_BOT_TOKEN"
#define TELEGRAM_CHAT_ID "YOUR_TELEGRAM_CHAT_ID"

#endif // TELEGRAM_CREDENTIALS_EXAMPLE_H
