/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 25.06.2026 14:05:40

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1472;
#else
constexpr int kTensorArenaSize = 448;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,104 } };
const TfArray<1, float> quant0_scale = { 1, { 0.049123093485832214, } };
const TfArray<1, int> quant0_zero = { 1, { -33 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 222, -155, -300, 294, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00015832456119824201, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[4*10] = { 
  68, 73, 127, -33, 1, -105, -122, -30, 120, 47, 
  69, -30, -94, -105, -96, -99, 19, 38, -52, 19, 
  -105, 90, -87, -92, 65, -101, 108, 54, 60, -65, 
  16, -20, -17, 43, 47, -36, 71, -35, -91, -113, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 4,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0057943528518080711, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 293, 33, 513, -407, 221, 531, -235, -78, 111, 251, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 9.7727475804276764e-05, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  29, -59, -76, 29, 90, 12, 124, -86, -6, -54, 37, 31, 74, 127, 68, -68, -4, -24, -62, 35, 
  -43, -110, 80, 70, 65, -26, -52, -95, -76, 32, -35, -51, 71, 21, 69, 82, -44, 29, -27, -18, 
  -26, -82, -5, 116, -35, -62, -45, 16, -41, 0, 49, 59, -26, -74, 1, -55, 76, -83, -105, -83, 
  45, -3, 82, -13, -72, 60, -61, -54, -36, 61, 81, 37, -82, -99, -10, -39, -35, -65, 93, 75, 
  -41, 71, -90, -35, -74, 70, -30, 38, -88, 58, 87, 59, -7, 61, 38, -90, -47, 99, 70, 53, 
  -83, 83, -76, 63, -40, -112, 7, 92, -109, -62, 92, 72, -60, 79, -5, -55, -45, 68, -82, 16, 
  97, 53, -44, -81, 83, 87, -4, -21, -15, 8, 49, 34, -71, -42, -1, -25, 63, -16, -24, -33, 
  -2, 82, 54, 52, 0, 95, 78, -111, 120, -20, -62, 103, 69, -34, -101, 43, 93, 3, 17, 83, 
  70, 32, 67, 43, 97, 43, -111, -34, -23, 24, 104, 16, 0, -110, -37, 87, -76, 62, -32, -31, 
  44, -73, -25, 11, 82, 108, -5, 3, 82, -80, -46, 49, -56, -56, 56, -20, -7, 80, 12, 83, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0040349052287638187, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 223, 219, 103, 316, 419, 479, 255, 265, 267, -119, 323, 102, 218, 352, 399, -193, 266, 12, -299, -15, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0001057436820701696, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*104] = { 
  -13, -17, -32, 74, 18, 28, 14, -69, 23, -94, -16, 22, -101, -76, 0, 82, 30, 86, -60, -59, 72, -39, 73, 2, -109, 48, -57, -54, -92, -122, -7, 21, 55, -94, -106, 26, -75, 62, -23, -75, 63, -24, -95, -52, -108, 62, -54, 71, -78, -86, -33, -101, 26, -12, -85, 63, 99, 54, 81, 55, 28, -50, 3, -85, -28, -82, -23, 23, 69, -12, 1, -110, -81, -48, -42, -77, 51, 29, -23, 63, 4, -20, -22, 20, -32, -1, -115, -27, -90, -107, 23, -39, -54, 76, -7, -91, 73, 30, -89, -58, -23, -121, 1, 33, 
  -78, -4, 55, 2, -44, 36, 35, 38, 45, 100, -55, 47, 16, 39, 42, -78, 86, 47, 122, -47, -4, -4, 86, -18, 48, 40, -4, 84, -48, -102, -44, 107, 92, 108, 67, -43, -91, -20, 16, -27, -65, -81, 109, 75, 72, -16, 85, -61, 14, 5, -90, -11, 24, -25, -38, -97, -90, 97, 88, -67, -3, 78, -29, -6, -9, 20, 71, -124, 76, -9, 110, -45, 71, -3, 13, 75, -39, -62, 7, 62, -41, -118, -65, -1, 51, 22, -20, -71, 21, -23, 38, 24, 68, 2, -17, 33, -41, -75, 24, -82, 31, 107, 9, -1, 
  54, -37, -76, -63, 53, -56, 63, 96, 102, -2, -75, 20, -74, 39, -46, 89, 52, 79, -1, 42, 97, -101, 49, -86, 4, -30, 86, 37, -49, -76, -43, 57, 42, -81, -25, -39, -88, -6, 58, -86, 42, 53, -75, 1, 34, -19, -54, -85, 30, -32, 44, -23, -29, -2, 71, -64, 28, 18, 17, -12, 100, -25, -13, 16, -26, 51, 26, -41, -19, -8, -5, -100, 10, 85, -14, -84, -82, 60, -61, -50, 38, -57, 42, -9, 4, 10, -29, -4, -82, 1, -76, 78, 47, -39, 127, 94, 33, 54, 45, 35, -93, -84, -53, -72, 
  -92, 54, -32, 80, 12, 63, 3, 111, 64, -73, 93, 95, 61, 58, 37, -2, -90, -56, 35, 73, -56, 55, -49, -21, 80, 70, -70, 35, 103, 83, -27, 49, 97, -32, 79, 33, 119, -78, 38, 64, -73, 80, -11, 65, 106, -66, 8, -52, 74, 60, -52, 11, -31, -96, 44, -91, -97, -91, -27, 1, 101, 47, 106, 83, -57, -92, 39, -62, -84, -114, 64, -42, -44, -59, 37, 52, -6, 120, 37, 119, 38, 78, 77, -19, -8, -74, 6, -23, 76, -26, 56, 45, -59, 27, 105, -16, -49, -9, 91, -12, -20, 3, 94, -48, 
  72, 8, 35, -80, -96, -82, 81, -29, -51, 56, -36, 15, -66, -53, -75, 74, 41, 49, -19, -31, -17, 88, -24, -20, -35, -1, 63, 46, -70, -96, 27, -74, 85, -78, -36, -53, -36, -96, 18, 51, 19, 46, -102, -51, 51, -69, 70, 57, -23, 64, 62, 70, -90, -41, -10, 79, 46, 73, 84, 52, -93, -87, 87, 89, 0, 50, -27, 124, -118, -47, -95, 24, 65, 31, 39, 45, -34, -30, -60, -21, 90, -104, 39, -80, 26, -66, 17, -77, 60, -42, -45, 0, 47, 81, 21, 0, 16, -27, -81, -83, -27, -94, 19, -34, 
  -55, 82, 14, 11, -18, -102, -13, 81, -61, 1, -115, -58, -120, 22, 4, -8, -83, 40, -52, -13, -101, -106, -31, -72, 54, -46, 14, -38, -63, 83, -29, -16, 71, -71, 11, -107, 60, -64, 36, 63, 72, 27, -52, -8, -6, -124, -99, -90, -25, 43, 68, -36, 9, -59, 68, 73, 45, -36, 34, -12, 4, -117, 45, -102, -50, -26, -58, 103, 77, 53, 69, -70, 45, -98, -124, -88, -33, -39, 48, -24, -96, 48, -33, 73, -21, -89, 17, -18, 88, -24, 4, -19, -52, 99, 26, 13, -35, 9, -24, 39, -35, 10, 60, -80, 
  56, -30, -44, -73, -78, -99, -36, 62, -45, 1, -11, -13, -2, 69, 19, -31, -54, -65, 103, 76, -49, 16, -51, 63, -43, -12, 105, -100, 72, 17, 55, -94, 4, -11, -82, 55, -99, 33, -90, 112, -2, 15, -6, 6, -47, -89, 97, -54, -7, -17, -63, 82, -80, 70, 21, -38, -16, 79, 50, -51, -72, 0, 65, -64, 45, 35, -108, 52, -78, -78, 21, 96, -27, 47, 25, 55, 38, 72, 47, -53, 68, 73, 8, 25, -64, -29, 62, 24, -53, -49, -78, 62, -56, 81, -52, -116, -51, -63, -101, -15, -68, -65, 0, -36, 
  90, -99, 7, 97, 93, 42, 38, 51, -23, 96, -11, 108, -26, 53, -76, -119, -21, -45, -56, 105, 94, -55, -43, 8, -14, 106, -14, 35, -114, -27, 6, 105, 32, -78, -28, -86, -10, 36, 78, -20, -37, 8, 117, 113, 47, 2, 32, -75, -49, 60, -59, -17, -3, 22, -53, -44, -73, 82, 78, -89, -57, -22, 63, -62, 65, 41, 33, -68, -30, 110, -48, 30, -7, 52, 9, 27, -29, 67, -39, 26, 78, -109, 46, 6, 37, -84, 52, 54, 77, -25, -15, -74, -8, -76, -99, -61, -22, -75, 15, 104, -21, 71, 7, -78, 
  43, 120, 64, -22, -91, 48, -29, -78, -26, -33, -10, 46, 42, -49, -3, -56, 29, -60, 86, 5, 78, 54, 75, 27, 47, 52, 60, 6, 68, -89, 55, -110, -31, -16, -98, -42, -103, 69, -82, -3, -45, -54, -90, -37, -100, 18, -48, -26, -67, 16, -107, -115, 87, -70, 44, 40, 6, 33, -25, -56, 48, -40, 68, -56, -10, -108, 70, 45, 63, -57, -53, -41, 4, -93, -44, -103, -87, -59, -69, 70, -55, -66, -89, -61, 70, 7, -20, 21, 44, 40, -15, -105, -111, -24, 64, -20, 78, 11, 29, -71, -86, -76, -60, 30, 
  -82, 18, -95, -2, -57, 62, -87, 12, -47, -94, -79, -63, -97, -24, -45, 76, 6, 78, 77, -59, -15, 68, 22, 95, 101, 67, 3, 41, -14, 31, -55, -29, -74, -2, 71, 28, 69, 77, -15, 18, 18, 28, -58, 18, -40, -98, 70, 43, 89, -76, 52, 103, -94, -83, -77, 33, 72, 17, -86, 45, -80, -46, -61, 83, 9, -22, -84, -38, -64, 63, -59, 68, 92, 5, -16, -74, 96, -24, -104, 76, 38, 84, -91, -57, -71, 79, -70, -55, 49, 19, 81, 38, -15, -28, 33, 112, 1, -91, -67, -39, 69, -74, -84, -31, 
  107, 18, 49, -102, -86, -21, 80, 36, 12, 54, -61, 52, 47, -56, 49, -56, 9, 16, 56, 43, -66, 68, -71, 103, 107, 6, -35, -33, 74, 76, -88, -65, -61, -4, 122, 112, -7, -59, -58, 47, 29, -20, 18, -16, -11, 92, 28, -75, 82, 61, -11, -41, -12, -5, 66, 71, -84, -23, 44, 3, 44, 54, 84, 85, 44, -75, -94, 57, 47, 26, 101, 34, -1, -20, 20, 113, 50, -40, 56, 112, -48, -56, 45, -51, -27, 82, -14, 48, -19, -29, 20, 104, 60, -55, -11, 10, -36, 56, -71, 68, 106, 81, 68, 60, 
  -7, 45, 86, -23, -71, -85, 106, -35, 79, -19, 92, 99, 70, 97, -54, 45, -46, -37, 97, 8, -18, -16, 102, 9, 36, 45, 70, 47, 92, 45, -3, -15, 9, -37, 32, -18, -66, 30, 32, 57, 42, 74, 88, -17, -49, -27, 27, 51, -83, -5, -72, 72, 38, 22, 83, 57, 48, -13, 16, -77, 82, 59, 2, -23, 77, 65, 66, -35, -18, -22, -73, 8, -53, -56, 86, 33, 48, 86, 51, 10, 40, 85, -91, -49, -89, -85, -60, 53, -6, 71, 57, -75, -112, -79, 3, 15, 49, 72, -12, -22, -8, -1, 81, 76, 
  -57, -108, 20, -51, 44, -94, -67, -108, -89, 40, -31, -102, 18, 45, -54, 77, -5, -52, 76, -35, 40, 48, -73, 55, 45, -40, -4, -54, 95, -14, -35, 17, -106, 85, 56, 57, 74, -73, -93, -71, 4, 34, -89, -56, -108, -47, 86, 51, -22, 94, 61, -99, -111, 11, -50, -124, -92, 24, -27, 33, -43, -83, -87, 59, 7, 17, 69, 42, 9, 56, -8, -54, 38, 58, 20, -107, -48, 68, -97, -72, 40, 66, 103, 57, 87, 71, -98, -63, -3, 55, -79, 82, 7, 23, -94, -112, 31, 4, 56, -30, -78, 52, 42, 24, 
  44, -102, -78, 8, 93, 117, -69, 111, 2, 41, 37, 43, 106, 44, -36, -95, -79, 2, -64, -20, -61, -65, 10, -18, -29, -86, -50, 103, -39, -7, 13, -80, -59, -82, 0, 38, 59, 7, 96, -14, 78, 27, 104, -53, 102, -33, 12, 73, 117, 77, 49, 62, -54, -52, 70, -26, 24, 88, 67, -2, 17, -18, 0, -61, 83, 93, 101, 55, 39, 102, -67, -3, 80, -4, 62, -61, -42, -34, 67, -82, -62, 32, -46, -16, 73, 34, 90, 103, 12, -83, 23, 38, -93, 33, -116, -93, -27, 113, 18, -35, 35, 106, 42, -57, 
  106, -106, -36, 24, 7, -42, -28, 52, 66, 52, 116, -82, -69, 110, -105, -21, -80, 23, 73, -65, 100, 114, -36, 90, -80, -44, 0, -101, 94, -24, 100, -38, -31, 76, 0, -50, -65, 39, 96, -81, -96, 96, -91, 72, 0, 79, -21, -48, -81, -27, -3, 62, 46, -28, -61, -80, 76, -6, 105, -40, 24, 60, -42, 109, 31, 102, 111, 84, -36, 34, 25, -46, 108, -25, 104, 65, -26, 42, 13, 26, 72, 8, -80, -29, 37, -65, 94, 26, -67, 37, -30, 48, 3, 59, -81, 0, 97, 97, 100, 120, -75, 112, -48, 93, 
  -19, 81, -56, -116, -114, 11, -27, 2, 22, 18, -22, 24, -73, 32, 64, 95, 6, 39, 20, 45, -108, 70, -98, 30, 10, -14, -64, -25, -3, -39, 45, -52, -53, 38, -23, 6, -15, -109, 9, 74, 74, -32, 17, -85, 57, -77, -105, -40, -89, 56, 27, -23, 52, 98, 59, -75, 76, 29, -88, 71, -13, -78, 3, -60, 0, 26, -6, -43, 11, 81, -102, 69, 68, 73, 28, 60, -56, 10, 66, 57, -54, -33, 39, 78, 84, 61, -6, 37, 42, 85, -20, 81, 42, 80, 116, 91, -99, 35, 38, 32, 62, 73, 81, -46, 
  -12, -51, -28, 4, 91, -40, -50, -88, 21, -105, -103, -48, 8, 36, -49, 53, -85, -58, 31, -47, -99, -72, 24, -58, 28, -48, -30, 86, -63, 57, 21, -14, 66, -75, -45, -68, 16, -100, -58, -11, 14, -9, 6, 61, -27, -97, 63, -110, -24, -56, -8, -28, -33, -92, -4, -80, 0, -37, 49, -86, -81, 72, -74, -9, -86, 31, 14, -28, -17, 89, -100, -38, -68, 71, 60, 37, -63, 12, -72, 1, 28, 76, -115, -44, -18, 56, -8, -75, 83, -36, 2, 84, 81, 33, 19, -49, -6, -47, 75, -63, -30, -29, -33, -29, 
  -29, 52, 92, 86, 90, -40, -49, 75, 24, -23, -46, 89, -45, 66, -81, -31, -65, 35, 85, -65, 45, -53, -85, 91, -63, -87, -58, 13, -5, -44, 1, -83, -3, 19, 3, 96, 92, -58, 68, -91, -96, -27, 106, -25, 23, -75, 1, 88, -85, 42, -54, -66, 84, 48, 39, -72, 80, -97, -31, -57, 21, -88, 39, 86, -30, 48, -28, 12, 31, -24, 70, -45, 57, 85, 40, 18, -88, -82, 67, -75, -81, -78, -75, 11, 45, 87, -46, 17, 17, 39, -8, 86, -83, -47, 81, 62, 35, -44, 82, -101, 79, 33, -1, -71, 
  -76, -12, 37, -83, 66, 16, -59, -2, 5, -29, -85, -32, -80, -63, -86, -64, 16, -53, -47, 47, -41, 93, -48, 86, -37, -82, 7, -26, -101, -61, 57, -35, -56, -81, 108, 87, 36, -61, -71, -25, -80, 23, -57, 54, 10, -8, 110, 31, -74, -86, 12, -79, 55, -45, 46, -57, -51, -57, -21, 81, -23, -45, -59, 88, 58, -43, 77, -91, 20, 106, 71, 62, 84, -38, -88, 38, 99, 27, -20, 32, 25, 41, 83, 5, 57, 27, 93, 17, 2, -75, -89, 90, 55, -35, -59, -61, 62, 30, 104, -55, -96, 107, 31, 18, 
  10, 97, 16, -71, -39, -24, 37, -15, 76, 74, -76, 87, 78, 18, -19, -52, -16, -99, -45, 36, -30, -84, 88, -72, 2, 12, -53, -51, 42, 91, -68, 27, 98, -53, 19, 44, -86, 29, 13, 9, -48, -56, 20, 47, 9, -76, -88, 36, 0, 14, 37, 54, -73, 31, 56, -79, 26, -80, -65, 78, -77, 68, -72, 41, -71, 4, -25, -64, -71, -89, -91, 76, -23, -7, -14, 42, -80, -95, -76, -56, 87, 10, 7, -75, -10, 47, 100, 0, 37, 9, -85, 27, -95, -12, 1, -112, -61, -66, 100, -56, -27, 83, 76, -71, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,104 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0021526266355067492, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.024220513179898262, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.027323940768837929, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,4 } };
const TfArray<1, float> quant9_scale = { 1, { 0.037277791649103165, } };
const TfArray<1, int> quant9_zero = { 1, { 17 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 104, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2080, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 112), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_944636_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_944636_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_944636_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_944636_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_944636_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
